# Generated by Django 5.2.14 on 2026-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_userloginrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='background',
            field=models.CharField(choices=[('white', 'White')], default='white', max_length=16),
        ),
    ]
