# Generated by Django 5.2.14 on 2026-05-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crop_head_ratio',
            field=models.FloatField(default=0.55),
        ),
    ]
